name: py38_dev
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip>=20.3
  - numpy>=1.23
  - scipy>=1.9
  - k3d==2.14.5
  - trimesh>=3.14
  - Pillow=9.2.0
  - imageio>=2.22
  - notebook>=6.5
  - tqdm
  - matplotlib
  - ipywidgets=7.5.1
  - scikit-image